# Generated by Django 5.0.2 on 2026-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_reply_wait",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Сколько минут ждать ответа клиента после того как менеджер написал",
                        verbose_name="Ожидание после ответа менеджера (мин)",
                    ),
                ),
                (
                    "first_reminder_delay",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="1 час 40 минут = 100",
                        verbose_name="Задержка первого напоминания (мин)",
                    ),
                ),
                (
                    "second_reminder_delay",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="5 часов = 300",
                        verbose_name="Задержка второго напоминания (мин)",
                    ),
                ),
                (
                    "close_delay",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="Сутки = 1440. Отсчёт идёт от момента когда лид впервые зафиксирован, не от последнего напоминания.",
                        verbose_name="Закрыть через N минут с момента создания лида",
                    ),
                ),
                (
                    "reactivation_delay",
                    models.PositiveIntegerField(
                        default=10080,
                        help_text="7 дней = 10080",
                        verbose_name="Задержка реактивации (мин)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки автоматизации",
                "verbose_name_plural": "Настройки автоматизации",
            },
        ),
        migrations.CreateModel(
            name="LeadAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID лида AmoCRM",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Телефон клиента"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID канала WazzUp"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый лид"),
                            ("waiting", "Ожидание ответа клиента"),
                            ("drip", "Дожим бот"),
                            ("closed", "Закрыт"),
                            ("human", "Нужен человек"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID задачи Celery"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Автоматизация лида",
                "verbose_name_plural": "Автоматизация лидов",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReminderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("first", "Первое напоминание (через 1ч40мин)"),
                            ("second", "Второе напоминание (через 5ч)"),
                            ("reactivation", "Реактивация (через 7 дней)"),
                        ],
                        max_length=20,
                        verbose_name="Этап",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Шаблон напоминания",
                "verbose_name_plural": "Шаблоны напоминаний",
            },
        ),
    ]
