# Generated by Django 5.0.2 on 2026-06-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remindermessage",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="URL изображения"),
        ),
        migrations.AlterField(
            model_name="automationconfig",
            name="second_reminder_delay",
            field=models.PositiveIntegerField(
                default=360,
                help_text="6 часов = 360. Отправляется только в 10:00–20:00 по Алматы, иначе откладывается до 10:00.",
                verbose_name="Задержка второго напоминания (мин)",
            ),
        ),
        migrations.AlterField(
            model_name="remindermessage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("first", "Первое напоминание (через 1ч40мин)"),
                    ("second", "Второе напоминание (через 6ч, только 10:00–20:00)"),
                    ("reactivation", "Реактивация (через 7 дней)"),
                ],
                max_length=20,
                verbose_name="Этап",
            ),
        ),
        migrations.AlterField(
            model_name="remindermessage",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст сообщения"),
        ),
    ]
