# Generated by Django 5.0.2 on 2026-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_remindermessage_image_url_and_more"),
    ]

    def rename_stages(apps, schema_editor):
        ReminderMessage = apps.get_model("automation", "ReminderMessage")
        ReminderMessage.objects.filter(stage="first").update(stage="Первое напоминание")
        ReminderMessage.objects.filter(stage="second").update(stage="Второе напоминание")
        ReminderMessage.objects.filter(stage="reactivation").update(stage="Реактивация")

    operations = [
        migrations.AlterField(
            model_name="remindermessage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("Первое напоминание", "Первое напоминание"),
                    ("Второе напоминание", "Второе напоминание"),
                    ("Реактивация", "Реактивация"),
                ],
                max_length=50,
                verbose_name="Этап",
            ),
        ),
        migrations.RunPython(rename_stages, migrations.RunPython.noop),
    ]
