# Generated by Django 5.0.2 on 2026-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_rename_stage_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadautomation",
            name="chat_type",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("instagram", "Instagram")],
                default="whatsapp",
                max_length=20,
                verbose_name="Тип чата",
            ),
        ),
        migrations.AlterField(
            model_name="leadautomation",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Телефон / Chat ID клиента"
            ),
        ),
    ]
