# Generated by Django 5.0.2 on 2026-07-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_add_chat_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationconfig",
            name="close_delay",
        ),
    ]
