# Generated by Django 5.0.2 on 2026-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_remove_close_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadautomation",
            name="amojo_talk_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="ID разговора AmoCRM",
            ),
        ),
        migrations.AddField(
            model_name="leadautomation",
            name="source",
            field=models.CharField(
                choices=[
                    ("wazzup", "WazzUp"),
                    ("amocrm_instagram", "AmoCRM Instagram"),
                ],
                default="wazzup",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
