# Generated by Django 5.0.2 on 2026-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_add_source_and_amojo_talk_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadautomation",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя клиента"
            ),
        ),
    ]
