# Generated by Django 5.0.2 on 2026-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0008_update_first_reminder_delay_to_120"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadautomation",
            name="wz_username",
            field=models.CharField(
                blank=True,
                help_text="Для привязки lead_id по полю контакта Instagram_WZ в AmoCRM — надёжнее, чем тег канала",
                max_length=100,
                verbose_name="Instagram юзернейм (WazzUp)",
            ),
        ),
        migrations.AlterField(
            model_name="automationconfig",
            name="first_reminder_delay",
            field=models.PositiveIntegerField(
                default=120,
                help_text="2 часа = 120",
                verbose_name="Задержка первого напоминания (мин)",
            ),
        ),
        migrations.AlterField(
            model_name="automationconfig",
            name="second_reminder_delay",
            field=models.PositiveIntegerField(
                default=360,
                help_text="6 часов = 360. Отправляется только в 10:00–21:00 по Алматы, иначе откладывается до 10:00.",
                verbose_name="Задержка второго напоминания (мин)",
            ),
        ),
    ]
